import { productDataType } from "./types";

export const productDataList: productDataType[] = [
  {
    name: "Burgundy Show",
    price: 15.0,
    id: "384e",
    category: "Bags",
    size: "XL",
    image: "/images/products/image_1.jpg",
    color: "#000",
  },
  {
    name: "Burgundy Suit",
    price: 125.0,
    id: "384e",
    category: "Bags",
    size: "XL",
    image: "/images/products/image_2.jpg",
    color: "#000",
  },
  {
    name: "Men Jacket",
    price: 20,
    id: "384e",
    category: "Jacket",
    size: "XL",
    image: "/images/products/image_3.jpg",
    color: "#000",
  },
  {
    name: "Burgundy Show",
    price: 15.0,
    id: "384e",
    category: "Bags",
    size: "XL",
    image: "/images/products/image_4.jpg",
    color: "#000",
  },
  {
    name: "Men Jacket",
    price: 20,
    id: "384e",
    category: "Jacket",
    size: "XL",
    image: "/images/products/image_5.jpg",
    color: "#000",
  },

  {
    name: "Men Jacket",
    price: 20,
    id: "384e",
    category: "Jacket",
    size: "XL",
    image: "/images/products/image_6.jpg",
    color: "#000",
  },
  {
    name: "Burgundy Show 4",
    price: 15.0,
    id: "384e",
    category: "Bags",
    size: "XL",
    image: "/images/products/image_1.jpg",
    color: "#000",
  },
  {
    name: "Men Jacket",
    price: 20,
    id: "384e",
    category: "Jacket",
    size: "XL",
    image: "/images/products/image_1.jpg",
    color: "#000",
  },
];
